dependent_dropdown/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dropdown.urls')),
]

dropdown/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.SubDistrictListView.as_view(), name='subdistrict_changelist'),
    path('', views.AreaCreateView.as_view(), name='area_add'),
    # path('<int:pk>/', views.SubDistrictUpdateView.as_view(), name='subdistrict_change'),


    path('ajax/load_districts/', views.load_districts, name='ajax_load_districts'),  # <-- this one here
    path('ajax/load_subdistricts/', views.load_subdistricts, name='ajax_load_subdistricts'),  # <-- this one here
]

dropdown/models.py
from django.db import models

class Division(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Division'

class District(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'District'

class SubDistrict(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Sub District'


class Area(models.Model):
    division = models.ForeignKey(Division, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    sub_district = models.ForeignKey(SubDistrict, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.division.name + ", " + self.district.name + ", " + self.sub_district.name
    
    class Meta:
        verbose_name_plural = 'Area'

dropdown/forms.py
from django import forms
from .models import *

class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        fields = ('division', 'district', 'sub_district')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['district'].queryset = District.objects.none()
        self.fields['sub_district'].queryset = SubDistrict.objects.none()

        if 'division' in self.data:
            try:
                division_id = int(self.data.get('division'))
                # district_id = int(self.data.get('sub_district'))
                self.fields['district'].queryset = District.objects.filter(division_id=division_id).order_by('name')
                # self.fields['sub_district'].queryset = SubDistrict.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['district'].queryset = self.instance.division.district_set.order_by('name')
            # self.fields['sub_district'].queryset = self.instance.district.sub_district_set.order_by('name')


        if 'district' in self.data:
            try:
                # division_id = int(self.data.get('division'))
                district_id = int(self.data.get('district'))
                # self.fields['district'].queryset = District.objects.filter(division_id=division_id).order_by('name')
                self.fields['sub_district'].queryset = SubDistrict.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            # self.fields['district'].queryset = self.instance.division.district_set.order_by('name')
            self.fields['sub_district'].queryset = self.instance.district.sub_district_set.order_by('name')

dropdown/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import *
from .forms import *

# class SubDistrictListView(ListView):
#     model = SubDistrict
#     context_object_name = 'subdistrict'

class AreaCreateView(CreateView):
    model = Area
    form_class = AreaForm
    success_url = '/thanks/'

# class SubDistrictUpdateView(UpdateView):
#     model = SubDistrict
#     form_class = SubDistrictForm
#     success_url = reverse_lazy('subdistrict_changelist')


def load_districts(request):
    division_id = request.GET.get('division')
    districts = District.objects.filter(division_id=division_id).order_by('name')
    return render(request, 'dropdown/district_dropdown_list_options.html', {'districts': districts})


def load_subdistricts(request):
    district_id = request.GET.get('district')
    subdistricts = SubDistrict.objects.filter(district_id=district_id).order_by('name')
    return render(request, 'dropdown/subdistrict_dropdown_list_options.html', {'subdistricts': subdistricts})

dropdown/templates/dropdown/area_form.html
<form method="post" id="areaForm" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_division").change(function () {
      var url = $("#areaForm").attr("ajax/load_districts/");  // get the url of the `load_cities` view
      var divisionId = $(this).val();  // get the selected country ID from the HTML input
    //   var districtId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: 'ajax/load_districts/',                  // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'division': divisionId ,      // add the country id to the GET parameters
        //   'district': districtId ,      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
  <script>
    $("#id_district").change(function () {
      var url = $("#areaForm").attr("ajax/load_subdistricts/");  // get the url of the `load_cities` view
      var districtId = $(this).val();  // get the selected country ID from the HTML input
    //   var districtId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: 'ajax/load_subdistricts/',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
        //   'division': divisionId ,      // add the country id to the GET parameters
          'district': districtId ,      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_sub_district").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

dropdown/templates/dropdown/district_dropdown_list_options.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}



<!-- <option value="">---------</option>
{% for x in subdistrict %}
<option value="{{ x.pk }}">{{ x.name }}</option>
{% endfor %} -->

dropdown/templates/dropdown/subdistrict_dropdown_list_options.html
<!-- <option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %} -->



<option value="">---------</option>
{% for x in subdistricts %}
<option value="{{ x.pk }}">{{ x.name }}</option>
{% endfor %}